<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-homehq-7960f3aa-fa61-47bc-94c0-e6949d10e4c6</UserSecretsId>
    <BlazorDisableThrowNavigationException>false</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="4.1.0" />
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="appdata\" />
    <Folder Include="docs\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeHQ.Application\HomeHQ.Application.csproj" />
    <ProjectReference Include="..\HomeHQ.Domain\HomeHQ.Domain.csproj" />
    <ProjectReference Include="..\HomeHQ.Infrastructure\HomeHQ.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="@(Content)">
      <Visible Condition="'%(NuGetItemType)' == 'Content'">false</Visible>
    </Content>
  </ItemGroup>

</Project>
